site_name: AWS Lambda Powertools for TypeScript
site_description: AWS Lambda Powertools for TypeScript
site_author: Amazon Web Services
repo_url: https://github.com/awslabs/aws-lambda-powertools-typescript
edit_uri: edit/main/docs

nav:
  - Homepage: index.md
  - Changelog: changelog.md
  - Roadmap: roadmap.md
  - API reference: api/" target="_blank
  - Core utilities:
      - core/tracer.md
      - core/logger.md
      - core/metrics.md

theme:
  name: material
  font:
    text: Ubuntu
  palette:
    - scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - header.autohide
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.instant
    - navigation.indexes
    - navigation.tracking
    - content.code.annotate
    - toc.follow
    - toc.integrate
    - announce.dismiss
  icon:
    repo: fontawesome/brands/github
  logo: media/aws-logo-light.svg
  favicon: media/aws-logo-light.svg
  custom_dir: docs/overrides

markdown_extensions:
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.details
  - pymdownx.snippets:
      base_path: "."
      check_paths: true
  - meta
  - toc:
      permalink: true
      toc_depth: 4
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

copyright: Copyright &copy; 2023 Amazon Web Services

plugins:
  - git-revision-date
  - search
  - exclude:
      glob:
        - snippets/node_modules/*
        - snippets/package.json

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascript/aws-amplify.min.js
  - javascript/extra.js

extra:
  version:
    provider: mike
    default: latest
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/awslabs/aws-lambda-powertools-typescript
    - icon: fontawesome/brands/discord
      link: https://discord.gg/B8zZKbbyET
      name: Join our Discord Server!
